version: '3'

services:
  linebot:
    build: .
    container_name: linebot
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Taipei
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
